name: dart_text
description: 
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.10.8

dependencies:
  dart_console: ^4.1.2
  path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
